# Generated by Django 5.0.6 on 2024-08-05 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_comment_author_remove_comment_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
